[workspace]
resolver = "2"
authors = ["Nathaniel Thomas <nathaniel@swbell.net>", "Bhargav Akula <mail.bhargavakula@gmail.com>"]
edition = "2024"
members = [ "oscps-db", "oscps-gui",
    "oscps-lib",
    ]
