[package]
name = "oscps-gui"
version = "0.1.0"
authors = ["Nathaniel Thomas <nathaniel@swbell.net>", "Bhargav Akula <bhargavakula01>"]
edition = "2021"

[dependencies]
iced = {version = "0.13.1", features = ["canvas", "debug", "lazy"]}
