name: Check Documentation

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          source $HOME/.cargo/env

      - name: Install cargo-doc-check
        run: cargo install cargo-doc-check

      - name: Check Documentation
        run: cargo doc-check
