name: Clippy and Documentation Check

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy with Documentation Lints
        run: cargo clippy -- -D warnings
